server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
    cloud:
      gateway:
        routes:
          - id: INVOICE-SERVICE
            uri: lb://INVOICE-SERVICE
            predicates:
              - Path=/invoices/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka